webserver:
  port: 8080

mongodb:
  host: localhost
  port: 27017
  username: test
  password: test
  database: kf66monico
  collections:
    session: session
    user: user
    call: call
    system: system

session:
  life: 259200

system:
  # default
  roujin_pass: test
