webserver:
  port: 8080
  basepath: /

mongodb:
  host: localhost
  port: 27017
  username: test
  password: test
  database: kf66monico
  collections:
    session: session
    user: user
    call: call
    system: system

# web system
system-db:
  host: localhost
  port: 27017
  username: test
  password: test
  database: kanaria

session:
  life: 259200

system:
  # default
  roujin_pass: test
  admin_pass: test
